[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=64BEF499DD9D4D949E43CA08B60AE04C
ProjectName=Apex Anglers: Shattered Waters
CompanyName=
CopyrightNotice=

[/Script/Engine.GameSession]
; GDD: 1-4 player co-op
MaxPlayers=4
